name: Static Site Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci || echo "No package.json detected, skipping..."

      - name: Run linter
        run: npm run lint || echo "No linter configured."

      - name: Run build script
        run: npm run build || echo "No build script."
